posts/forms.py
#wtforms
from flask_wtf import FlaskForm

from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired



class PostForm(FlaskForm):
    title = StringField('Заголовок:', validators=[DataRequired()])
    body = TextAreaField('Пост:', validators=[DataRequired()])

posts/blueprint.py
#flask
from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for

#WTForm
from flask_wtf import FlaskForm
#flask_security
from flask_security import login_required

#project
from models import Post
from .forms import PostForm
from app import db

posts = Blueprint('posts', __name__, template_folder='templates', static_folder='../static')


# http://localhost/blog /create
@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Не удалось добавить пост')

        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create.html', form=form)

# http://localhost/blog /<slug>/edit
@posts.route('/<slug>/edit', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first()

    if request.method == 'POST':
        # Наполнение формы данными
        form = PostForm(formdata=request.form, obj=post)
        # Получение новых данных
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))

    form = PostForm(obj=post)
    return render_template('posts/edit.html', post=post, form=form)


# http://localhost/blog
@posts.route('/')
def index():
    # Pagination
    # /blog/?page=
    page = request.args.get('page') 
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    # Search
    q = request.args.get('q')
    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
        
    else:
        posts = Post.query.order_by(Post.created.desc())

    # Pagination
    pages = posts.paginate(page=page, per_page=5)

    return render_template('posts/index.html', posts=posts, pages=pages)

# http://localhost/blog /<slug>
@posts.route('/<slug>')
def post_detail(slug):
    # Search
    q = request.args.get('q')
    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q)).all()
        return render_template('posts/index.html', posts=posts)

    post = Post.query.filter(Post.slug==slug).first()
    if post:
        tags = post.tags
        return render_template('posts/detail.html', post=post, tags=tags)
    else:
        return redirect(url_for('posts.index'))

tags/blueprint.py
#flask
from flask import Blueprint, redirect, url_for
from flask import render_template
from flask import request

#project
from models import Post, Tag

tags = Blueprint('tags', __name__, template_folder='templates', static_folder='../static')

@tags.route('/')
def index():
    # Search
    q = request.args.get('q')
    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q)).all()
        return render_template('posts/index.html', posts=posts)
    
    tags = Tag.query.all()
    return render_template('tags/index.html', tags=tags)

# http://localhost/ tag/<slug>
@tags.route('/<slug>')
def tag_detail(slug):
    # Search
    q = request.args.get('q')
    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q)).all()
        return render_template('posts/index.html', posts=posts)

    tag = Tag.query.filter(Tag.slug==slug).first()
    if tag:
        posts = tag.posts.all()
        return render_template('tags/detail.html', posts=posts, tag=tag)
    else:
        return redirect(url_for('tags.index'))

posts/templates/posts/create.html
{% extends "base.html" %}

{% block title %}
    Новый пост
{% endblock %}

{% block content_title %}
    Новый пост
{% endblock %}

{% block content %}
    <div class="col-md-6">
        <form action="{{ url_for('posts.create_post') }}" method="post" name="create_post">
            {{ form.hidden_tag() }}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label(class='control-label') }}
                    {{ field(class='form-control') }}
                </div>
            {% endfor %}
            <div class="mt-3">
                <button type="submit" class="btn btn-dark">Создать</button>
            </div>
        </form>
    </div>
{% endblock %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content_title %}
    {{ post.title }}
{% endblock %}


{% block content %}
    <div class="tags">
        {% for tag in tags %}
            <a href="{{ url_for('tags.tag_detail', slug=tag.slug) }}">
                <span class="badge bg-success">{{ tag.name }}</span>
            </a>
        {% endfor %}
    </div>
    <div class="main-content">
        {{ post.body|markdown }}
    </div>
{% endblock %}

posts/templates/posts/edit.html
{% extends "base.html" %}

{% block title %}
    Редактирование поста
{% endblock %}

{% block content_title %}
    Редактирование поста
{% endblock %}

{% block content %}
    <div class="col-md-6">
        <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="post">
            {{ form.hidden_tag() }}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label(class='control-label') }}
                    {{ field(class='form-control') }}
                </div>
            {% endfor %}
            <div class="mt-3">
                <button type="submit" class="btn btn-dark">Сохранить</button>
            </div>
        </form>
    </div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Все записи
{% endblock %}

{% block content_title %}
    Все записи
{% endblock %}

{% block content %}
    {% for post in pages.items %}
        <p>
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
        </p>
    {% endfor %}

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">

            <li {% if not pages.has_prev %} class="page-item disabled"{% endif %}>
                <a class="page-link" href="./?page={{ pages.prev_num }}" tabindex="-1"> << </a>
            </li>

            {% for page in pages.iter_pages() %}

                <li class="page-item {% if page == pages.page %}active{% endif %}">
                    <a class="page-link" href="./?page={{ page }}">
                        {{ page }}{% if page == pages.page %}<span class="sr-only"></span>{% endif %}
                    </a>
                </li>

            {% endfor %}

            <li {% if not pages.has_next %} class="page-item disabled"{% endif %}>
                <a class="page-link" href="./?page={{ pages.next_num }}"> >> </a>
            </li>

            </li>
        </ul>
    </nav>


{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content_title %}
    {{ post.title }}
{% endblock %}


{% block content %}
    <div class="tags">
        {% for tag in tags %}
            <a href="{{ url_for('tags.tag_detail', slug=tag.slug) }}">
                <span class="badge bg-success">{{ tag.name }}</span>
            </a>
        {% endfor %}
    </div>
    <div class="main-content">
        {{ post.body }}
    </div>
{% endblock %}